from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    """ Represents a single post"""
    author = models.ForeignKey(User, on_delete=models.PROTECT,
                               help_text="The user that posted this post.")
    slug = models.CharField(max_length=600, blank=True, editable=False,
                            help_text="Unique URL path to access this post. Generated by the system.")
    content = models.TextField(
        help_text="Write the content of your page here.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this page was created. Automatically generated when the model saves.")
    

    def get_absolute_url(self):
        """ Returns a fully-qualified path for a page (/my-new-media-post). """
        path_components = {'slug': self.slug}
        return reverse('meida-details-post', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a post is created. """
        if not self.pk:
            self.slug = slugify(self.content , allow_unicode=True)

        # Call save on the superclass.
        return super(Post, self).save(*args, **kwargs)